{
"login": "ppark482",
"id": 8863462,
"avatar_url": "https://avatars.githubusercontent.com/u/8863462?v=2",
"gravatar_id": "",
"url": "https://api.github.com/users/ppark482",
"html_url": "https://github.com/ppark482",
"followers_url": "https://api.github.com/users/ppark482/followers",
"following_url": "https://api.github.com/users/ppark482/following{/other_user}",
"gists_url": "https://api.github.com/users/ppark482/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ppark482/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ppark482/subscriptions",
"organizations_url": "https://api.github.com/users/ppark482/orgs",
"repos_url": "https://api.github.com/users/ppark482/repos",
"events_url": "https://api.github.com/users/ppark482/events{/privacy}",
"received_events_url": "https://api.github.com/users/ppark482/received_events",
"type": "User",
"site_admin": false,
"name": "Paul Park",
"company": "",
"blog": "http://paul.gg",
"location": "",
"email": "",
"hireable": false,
"bio": null,
"public_repos": 9,
"public_gists": 0,
"followers": 0,
"following": 0,
"created_at": "2014-09-22T16:04:48Z",
"updated_at": "2014-10-08T16:10:21Z"
}
